apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi-controller.fullname" . }}
  labels:
    {{- include "unifi-controller.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 3478
      targetPort: stun
      protocol: UDP
      name: stun
    - port: 10001
      targetPort: ap-discovery
      protocol: UDP
      name: ap-discovery
    - port: 8080
      targetPort: http-devices
      protocol: TCP
      name: http-devices
    - port: 8443
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "unifi-controller.selectorLabels" . | nindent 4 }}
